# line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '7.0'
target ‘PushNotificationsText’ do
    
pod 'AFNetworking','3.1.0'
end

target ‘PushNotificationsTextTests' do

end